### ISSUE TITLE
Enable/disable log message categories at runtime

### ISSUE THREAD

**Issue by MeanSquaredError** [rbeeli/websocketclient-cpp#12]
Currently the custom logger allows enabling/disabling log messages at runtime depending on their loglevel. 

There are also log message categories that can be enabled/disabled via defines:
```
WS_CLIENT_LOG_HANDSHAKE
WS_CLIENT_LOG_MSG_PAYLOADS
WS_CLIENT_LOG_MSG_SIZES
WS_CLIENT_LOG_FRAMES
WS_CLIENT_LOG_COMPRESSION
```
These message categories can only be enabled/disabled via defines, but it also makes sense to enable/disable them at runtime.

For example if the user suspects that the server sends him wrong information, he may temporarily enable logging of message payloads (`WS_CLIENT_LOG_MSG_PAYLOADS`) in the program config file, troubleshoot the problem and then disable it again in the config file.

Currently it is not possible to do that by disabling messages by message level because message payloads are logged at the info level (`Level::I`), which is a relatively high level. If the user disabled messages at the info level and below, he might miss some useful messages.

So it probably makes sense to add a message category too and enable/disable the category at runtime by calling methods like 

```
template <LogCategory category>
is_category_enabled()
```
which is similar to the current
```
template <LogLevel level>
is_enabled()
```

Alternatively another probably easier solution would be to move the payload logging to another log level, e.g. `trace`, which is more verbose than the `debug` level, so the log levels would be :
```
// 0 = disabled, 1 = error, 2 = warning, 3 = info, 4 = debug, 5 = trace
enum class LogLevel : uint8_t
{
    N = 0, // Disabled
    E = 1, // Error
    W = 2, // Warning
    I = 3, // Info
    D = 4,  // Debug
    T = 5 // Trace
};
```
This would allow cutting off the payload logging at runtime without affecting the other log messages.

**Comment by MeanSquaredError** [comment]
Actually after giving the problem more though, I came up with another idea. Maybe it would be easier to change these defines:
```
WS_CLIENT_LOG_HANDSHAKE
WS_CLIENT_LOG_MSG_PAYLOADS
WS_CLIENT_LOG_MSG_SIZES
WS_CLIENT_LOG_FRAMES
WS_CLIENT_LOG_COMPRESSION
```
from a boolean (0 or 1) to a numeric constant equivalent to one of of `LogLevel` constants, so that
```
0 means that logging of the corresponding category is disabled
1 means log at the error level
2 means log at the warning level
3 means log at the info level
4 means log at the debug level
5 means log at the trace level (provided that this extra constant is added)
```

I can provide a PR for this feature if you think that it makes sense.

**Comment by rbeeli** [comment]
Hi,

Yes, I had this approach in my mind in the past as well, just didn't bother implementing it yet.

The solution to have runtime-adjustable logging, but still maintain the ability to optimize away all logging code, is to keep the define flags (or potentially something `constexpr`), but additionally pass a log category to the logger call. If we want runtime-adjustable logging, we can set all defines to `1`, so all logging code is compiled, and do the category/level filtering in the logger implementation itself, which will get the level and category as parameters.

Log-level per category is something to think about.

I'll look into it next week, I also have switching from `std::stringstream` to `fmt` form the standard on my to-do list, which could be tackled together.

**Comment by MeanSquaredError** [comment]
Great. Thank you for looking into this issue. 

Switching from `std::stringstream` to `std::format` will definitely simplify building the log messages.

Essentially what I (and probably other users) need is the ability to turn on/off at runtime the logging of payload data. It takes lots of space in the logs, so by default it should be turned off. But if a problem is found it should be possible to turn it on temporarily without recompiling the executable.

There are various ways to tackle this issue and I am not sure what is the best one.
The simplest solution would be to change the category defines (`WS_CLIENT_LOG_MSG_PAYLOADS`, etc) from boolean (`0`or `1`) to log levels (`0` to `4`) for the corresponding categories. Then use the runtime-configurable log level to cut off logging for the messages at the specified category, including the unwanted categories. This has the added benefit that if the corresponding category (e.g. `WS_CLIENT_LOG_MSG_PAYLOADS`) has the value `0` (which is equivalent to `LogLevel::N`), then its logging code will be completely removed from the compiled executable. I imaging that the code would be something like this:
```
#if WS_CLIENT_LOG_MSG_PAYLOADS
    logger_->template log<static_cast<LogLevel> (WS_CLIENT_LOG_MSG_PAYLOADS)>(std::format (...));
#endif
```

But then again there could be other, better approaches. I am fine with any approach as long as the different categories (more specifically payloads) can be skipped at runtime from logging.

**Comment by rbeeli** [comment]
Hi,

I have implemented log topics and levels per topic, runtime-adjustable and thread-safe.

Please note that the `WS_CLIENT_LOG_*****` defines have changed and now represent the default log levels, `0` will optimize away the logging code for that respective topic.

Also note that the `ConsoleLogger` type signature has changed, the min. log level is not a template parameter anymore, but a constructor parameter instead, see examples.

Check the [README](https://github.com/rbeeli/websocketclient-cpp/blob/main/README.md) for more information, also see this example [examples/builtin/ex_echo_builtin.cpp](https://github.com/rbeeli/websocketclient-cpp/blob/main/examples/builtin/ex_echo_builtin.cpp) which changes the log level of some topics at runtime after logger creation using the `set_level` function.

If anything is unclear, let me know.

**Comment by MeanSquaredError** [comment]
Great! Thank you very much for the updates, they are exactly what I need.
