### ISSUE TITLE
Handling EINTR errors for I/O operations

### ISSUE THREAD

**Issue by MeanSquaredError** [rbeeli/websocketclient-cpp#2]
Hi,

After looking into the library's source code it seems that the library does not handle EINTR errors that happen when:
- The program has established a handler for some interrupt.
- The interrupt is signaled while the process is sleeping on a "slow" I/O operation, e.g. socket poll or socket read.
- The interrupt handler is set without the SA_RESTART flag or the flag is set, but the operation is not restartable automatically, e.g. socket recv with a timeout.
- The handler processes the interrupt and then returns without terminating the program.

If these conditions are met, then the I/O operation fails with an EINTR error code.

This problem can happen easily when the program has established a handler for SIGINT in order to shutdown gracefully or re-read its configuration when it receives the signal.

The usual workaround for this issue is just retrying the I/O operation when it returns EINTR. In pseudocode it looks like this:
```
do {
    auto error_code = read (...);
} while (error_code == EINTR);
```

**Comment by rbeeli** [comment]
Hi,

Where did you check, and which socket client implementation did you consider?

Both built-in synchronous socket clients `TcpSocket` and `OpenSslSocket` have a check for `EINTR`:

https://github.com/rbeeli/websocketclient-cpp/blob/main/include/ws_client/transport/builtin/OpenSslSocket.hpp#L257

https://github.com/rbeeli/websocketclient-cpp/blob/main/include/ws_client/transport/builtin/TcpSocket.hpp#L248

If you experience a specific error or unexpected result, please provide a MWE.

**Comment by MeanSquaredError** [comment]
Indeed I did not notice that tcp/ssl reads and writes have the check for `EINTR`.
However the `connect()` and `SSL_connect` are lacking the checks for `EINTR` and they can fail with EINTR too.

**Comment by rbeeli** [comment]
You are right, those function slipped my attention regarding `EINTR`, will look into it next week. Thanks.

**Comment by rbeeli** [comment]
`connect` and `SSL_connect` are now checked for `EINTR` in `TcpSocket` and `OpenSslSocket`.

**Comment by MeanSquaredError** [comment]
Thank you for fixing that!
