### ISSUE TITLE
GCC build error

### ISSUE THREAD

**Issue by MeanSquaredError** [rbeeli/websocketclient-cpp#7]
Downloading and building the project with GCC results an error:
```
root@fedora:/usr/local/projects/github/websocketclient-cpp# cmake --preset gcc_dev_install
Preset CMake variables:

  CMAKE_BUILD_TYPE="Release"
  CMAKE_CXX_COMPILER="/usr/bin/g++"
  CMAKE_CXX_FLAGS="-fcoroutines -Wall -Wpedantic -Wextra -fno-rtti -Wno-unused-parameter -Wno-unused-function -Werror=return-type -Woverloaded-virtual -Wnon-virtual-dtor -Wno-ignored-attributes -g1 -O3 -flto=auto -DNDEBUG"
  CMAKE_INSTALL_PREFIX="/usr/local/projects/github/websocketclient-cpp/build/gcc/dev_install"
  CMAKE_MAKE_PROGRAM="make"
  CMAKE_TOOLCHAIN_FILE:FILEPATH="/scripts/buildsystems/vcpkg.cmake"
  VCPKG_OVERLAY_TRIPLETS="/usr/local/projects/github/websocketclient-cpp/triplets"
  VCPKG_TARGET_TRIPLET="x64-linux"

Preset environment variables:

  CMAKE_CXX_FLAGS="-fcoroutines -Wall -Wpedantic -Wextra -fno-rtti -Wno-unused-parameter -Wno-unused-function -Werror=return-type -Woverloaded-virtual -Wnon-virtual-dtor -Wno-ignored-attributes"
  __DISABLED="-fno-exceptions -Wfatal-errors -Wunused -Wconversion"

CMake Error at /usr/share/cmake/Modules/CMakeDetermineSystem.cmake:176 (message):
  Could not find toolchain file: /scripts/buildsystems/vcpkg.cmake
Call Stack (most recent call first):
  CMakeLists.txt:8 (project)


-- Configuring incomplete, errors occurred!
root@fedora:/usr/local/projects/github/websocketclient-cpp# 
```

I think that this is a new error introduced with some of the latest commits because a few months ago I was able to build the project without a problem.

**Comment by rbeeli** [comment]
Hi,

The error says `Could not find toolchain file: /scripts/buildsystems/vcpkg.cmake`

Do you have `vcpkg` correctly installed? The build is currently based on `vcpkg`, so `VCPKG_ROOT` env var should be set, or `CMAKE_TOOLCHAIN_FILE` should be overridden see https://github.com/rbeeli/websocketclient-cpp/blob/main/CMakePresets.json#L21

**Comment by rbeeli** [comment]
Probably should be documented more clearly.

If you don't want to compile the examples, you could generate the cmake files and copy header files into the `build/install` subfolder like this:

```bash
cmake -S . -B build -DCMAKE_INSTALL_PREFIX=build/install
cmake --install build
```

Would have to check what's the best practice, open for suggestions or PRs.

**Comment by MeanSquaredError** [comment]
I didn't have `vcpkg` installed, but after installing it, I am getting pretty much the same error
```
root@fedora:/usr/local/projects/github/websocketclient-cpp# vcpkg --version
vcpkg package management program version 2024-06-10-1.fc40

See LICENSE.txt for license information.
root@fedora:/usr/local/projects/github/websocketclient-cpp# echo $VCPKG_ROOT
/root/.local/share/vcpkg
root@fedora:/usr/local/projects/github/websocketclient-cpp# cmake --preset gcc_dev_install
Preset CMake variables:

  CMAKE_BUILD_TYPE="Release"
  CMAKE_CXX_COMPILER="/usr/bin/g++"
  CMAKE_CXX_FLAGS="-fcoroutines -Wall -Wpedantic -Wextra -fno-rtti -Wno-unused-parameter -Wno-unused-function -Werror=return-type -Woverloaded-virtual -Wnon-virtual-dtor -Wno-ignored-attributes -g1 -O3 -flto=auto -DNDEBUG"
  CMAKE_INSTALL_PREFIX="/usr/local/projects/github/websocketclient-cpp/build/gcc/dev_install"
  CMAKE_MAKE_PROGRAM="make"
  CMAKE_TOOLCHAIN_FILE:FILEPATH="/root/.local/share/vcpkg/scripts/buildsystems/vcpkg.cmake"
  VCPKG_OVERLAY_TRIPLETS="/usr/local/projects/github/websocketclient-cpp/triplets"
  VCPKG_TARGET_TRIPLET="x64-linux"

Preset environment variables:

  CMAKE_CXX_FLAGS="-fcoroutines -Wall -Wpedantic -Wextra -fno-rtti -Wno-unused-parameter -Wno-unused-function -Werror=return-type -Woverloaded-virtual -Wnon-virtual-dtor -Wno-ignored-attributes"
  __DISABLED="-fno-exceptions -Wfatal-errors -Wunused -Wconversion"

CMake Error at /usr/share/cmake/Modules/CMakeDetermineSystem.cmake:176 (message):
  Could not find toolchain file:
  /root/.local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
Call Stack (most recent call first):
  CMakeLists.txt:8 (project)


-- Configuring incomplete, errors occurred!
```

I will investigate this in more detail and will let you know my findings.

**Comment by MeanSquaredError** [comment]
This command worked correctly even without `vcpkg` installed.
Thank you!

> If you don't want to compile the examples, you could generate the cmake files and copy header files into the `build/install` subfolder like this:
> 
> ```shell
> cmake -S . -B build -DCMAKE_INSTALL_PREFIX=build/install
> cmake --install build
> ```

**Comment by MeanSquaredError** [comment]
Actually with the above command, the initial step didn't generate an error, but after that the headers were installed in `/usr/local/projects/github/websocketclient-cpp/build/install/include`
which is not exactly what I need. Normally on Fedora, the custom project headers go to
`/usr/local/include`
`websocketclient-cpp` from a couple of months ago installed all headers and cmake files correctly.

**Comment by rbeeli** [comment]
Then you can leave away the install prefix parameter to install it on the system default location:

```
cmake -S . -B build
cmake --install build
```

Second command might require `sudo`, i.e. `sudo cmake --install build`.

**Comment by MeanSquaredError** [comment]
OK, it did configure, build and install correctly after running:
```
cmake -B build
cmake --build build
cmake --install build
```
So I guess the `vcpkg` problem is caused by the presets used with `--preset gcc_dev_install`

Thanks for the help!
