### ISSUE TITLE
ws_client::URL::parse(const string& url)

### ISSUE THREAD

**Issue by MeanSquaredError** [rbeeli/websocketclient-cpp#9]
I think that it makes sense to change the signature of
```
ws_client::URL::parse(const string& url)
```
to
```
ws_client::URL::parse(string_view url)
```
This way it will be possible to call the `parse` method with a `string_view` argument without having to explicitly construct a string.

If you too think that it makes sense, I can provide a PR.

**Comment by rbeeli** [comment]
Agreed, I'll look into it, thanks.

**Comment by rbeeli** [comment]
Implemented.

**Comment by MeanSquaredError** [comment]
Thank you!
